### PR TITLE
Disable dial-in

### PR DESCRIPTION
**Pull request by mrose17**
If approved, please *do not merge*.

### CODE REVIEW

**Review by tackley — APPROVED** [review]

**Review by tackley — APPROVED** [review]
Still looks good to me :)

**Comment by alihamze** [comment]
Is there a reason for disabling dial-in numbers? Are they going to be coming back or was this intentional? I see the original PR says not to merge so wondering if it was an accident or not

**Comment by mrose17** [comment]
_sigh_ - the confusion is my fault for not updating the issue. our normal process for this repo is that once a PR gets approved in the `prod` branch, it goes into production. in this case, i wanted the PR approved but the merge to be put on hold awaiting final confirmation. We got that 11 days ago, did the merge, **and then i forgot to update the issue indicating that**.

**Comment by mrose17** [comment]
as to the more substantive question: the fundamental problem is that use of POTS to access a conference introduces additional privacy concerns.

**Comment by PrivacyMatters** [comment]
Brave Talk is a web browser service. Dial In is temporarily disabled while it undergoes an additional data protection & privacy review.

**Pull request merged**
