### PR TITLE
Add spam_score filtering for NFT collection token-gating

### LINKED ISSUE #1197: Add `spam_score` filtering for NFT collection token-gating
At present, the `spam_score` filtering for an NFT is shown only when selecting an avatar. Please add the filtering for the NFT collection token-gating (both to participate and to moderate). As usually, if at least one NFT comes from a spammy colletction, make the "Show all NFTs (not all being shown)" box present and filter accordingly...

### PR DESCRIPTION
**Pull request by bcaller**
Closes #1197

### CODE REVIEW

**Comment by bcaller** [comment]
image

**Comment by bcaller** [comment]
Cherry-picked onto dev1

**Review by mrose17 — APPROVED** [review]
Looks good on `dev1`

**Comment by mrose17** [comment]
@bcaller - go ahead and merge and test on staging!

**Pull request merged**
