### PR TITLE
fix: correct meta description tag

### PR DESCRIPTION
**Pull request by AlanBreck**

### CODE REVIEW

**Review by mrose17 — APPROVED** [review]
Simple and effective.

**Review by DJAndries — APPROVED** [review]

**Comment by AlanBreck** [comment]
Anything I need to do further with this?

**Comment by mrose17** [comment]
> Anything I need to do further with this?

No! It's in the pipeline... Estimated deploy to production is on Monday. Will that work?

**Comment by AlanBreck** [comment]
Works for me! Thank you.

**Pull request merged**
