### PR TITLE
Added more failure messages (context to error status codes)

### PR DESCRIPTION
**Pull request by alanzhng**
c.f., https://github.com/brave/brave-talk/issues/314

### CODE REVIEW

**Comment by alanzhng** [comment]
Added a couple new failureMessages that I felt were relevant to test. The messages are generic (e.g "Forbidden") and can definitely be changed to describe specifically what is going wrong with Talk / the subscription service.

@rmcfadden3, could you take a look and comment on the wording of these failure messages?

**Comment by rmcfadden3** [comment]
@alanzhng — they seem ok, though note we should default to sentence case whenever possible. So edit to:

      403: "Forbidden",
      405: "Method not allowed",
      408: "Request timeout",
      417: "Expectation failed",
      420: "Method failure",
      429: "Too many requests",
      500: "Internal server error",
      502: "Bad gateway",
      503: "Service unavailable",
      504: "Gateway timeout",

Also, question: Are these Brave Talk errors? If yes, we had an earlier thread where we discussed defaulting to "Call" rather than "Room" for the atomic unit the user creates or participates in. You start a call, end a call, join a call, etc. So anyways if this is for Talk, would suggest changing the following as well:

      404: "The call does not exist",
      409: "Sorry, call already exists! (this should not happen)",

**Comment by alanzhng** [comment]
Will do!

Yes, these are Brave Talk errors. I completely agree that "call" is the most clear and leaves zero room for confusion.

**Comment by mrose17** [comment]
@alanzhng - great! the next step is to add the JP language localizations since the fix for https://github.com/brave/brave-talk/issues/11 is now in `main` ...

here's how to do that:

1. Click the `Update branch` button above and then get the latest version of `issue314`

**Comment by mrose17** [comment]
@alanzhng - great! the next step is to add the JP language localizations since the fix for https://github.com/brave/brave-talk/issues/11 is now in `main` ...

here's how to do that:

1. Click the `Update branch` button above and then get the latest version of `issue314`
2. Take a look at https://github.com/brave/brave-talk/pull/333/files to see how @hadiamjad add support for the Status check link
3. Get the JP translations - abdul will explain the process

Good luck!

**Review by mrose17 — APPROVED** [review]
Good catch!

**Review by mrose17 — APPROVED** [review]
Looks good on the development server and to me.

**Pull request merged**
